### ISSUE TITLE
Testing using webcam

### ISSUE THREAD

**Issue by thanhsang298** [rabBit64/Sign-language-recognition-with-RNN-and-Mediapipe#25]
Can I do the testing through my webcam?
thank you :D

**Comment by Alex-Beh** [comment]
@thanhsang298 Hello, may I know have you try this repo with the input from webcam? Do you mind to share your experience on that? Thanks in advance

**Comment by thanhsang298** [comment]
> @thanhsang298 Hello, may I know have you try this repo with the input from webcam? Do you mind to share your experience on that? Thanks in advance
Sorry, I was not interested in and stopped that.
I used a GUI, writting with Tkiner library instead of testing on webcam
