### ISSUE TITLE
I don't get the features text file

### ISSUE THREAD

**Issue by rami-alloush** [rabBit64/Sign-language-recognition-with-RNN-and-Mediapipe#5]
I followed all the steps and I get the video file correctly in the output (_Word) (with the features visually on it).
The folder for the text file (Word) is created but it's always empty.
Where should I look?
Thanks

**Comment by cassioalmeidas** [comment]
@rami-alloush how is your input and output folders named?

**Comment by peppe1995romano** [comment]
@rami-alloush you probably have spaces or _ in the folder name, ex. "input_video" it's wrong, use "inputvideo"

**Comment by rami-alloush** [comment]
Thank you, I did two things and things are working fine now:
1. I made sure folder names are correct
2. The mediapipe folder is not renamed to anything else.
Thanks all
